"""review shops2

Revision ID: 52f7c6aede66
Revises: 7d884011ac10
Create Date: 2025-04-30 12:11:23.803761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52f7c6aede66'
down_revision: Union[str, None] = '7d884011ac10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shops', 'link_photo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shops', 'link_photo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
