"""add column in users: email, number_phone, password

Revision ID: f326fbdb677a
Revises: 3efac5b14604
Create Date: 2025-04-24 18:45:22.035992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f326fbdb677a'
down_revision: Union[str, None] = '3efac5b14604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('number_phone', sa.BigInteger(), nullable=False))
    op.add_column('users', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    op.drop_column('users', 'number_phone')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
