"""review table users

Revision ID: 255978f90764
Revises: f326fbdb677a
Create Date: 2025-04-24 18:47:05.696510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '255978f90764'
down_revision: Union[str, None] = 'f326fbdb677a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'link_photo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'about_me',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'about_me',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'link_photo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
