"""review struct models orm

Revision ID: e9d8726ca87b
Revises: add34e659620
Create Date: 2025-04-29 16:40:01.834674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9d8726ca87b'
down_revision: Union[str, None] = 'add34e659620'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'shops', 'users', ['user_id'], ['id'])
    op.drop_constraint('users_shop_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'shop_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('shop_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_shop_id_fkey', 'users', 'shops', ['shop_id'], ['id'])
    op.drop_constraint(None, 'shops', type_='foreignkey')
    op.drop_column('shops', 'user_id')
    # ### end Alembic commands ###
