"""review table users

Revision ID: c8fe953644a6
Revises: 737710f07b42
Create Date: 2025-04-24 19:56:29.279386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8fe953644a6'
down_revision: Union[str, None] = '737710f07b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'number_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('users_number_phone_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_number_phone_key', 'users', ['number_phone'])
    op.alter_column('users', 'number_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
